name: "todo"
mode: "dev"
port: 8084
version: "v0.0.1"
start_time: "2024-01-25"
machine_id: 1

log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "root"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 100